host: 'localhost'
port: 8848
namespace: 'd66fce99-0537-41ba-bd94-aa2d50f4197d'
user: 'nacos'
password: 'nacos'
dataid: 'inventory-srv.json'
group: 'pro'

#name: 'user-srv'
#mysql:
#  host: 'localhost'
#  port: 3306
#  user: 'root'
#  password: '123456'
#  db: 'mxshop_inventory_srv'
#
#consul:
#  host: '192.168.181.130'
#  port: 8500