host: 'localhost'
port: 8848
namespace: '6af9810f-2e08-4e9e-ab52-ae2868fe5fcc'
user: 'nacos'
password: 'nacos'
dataid: 'user-srv.json'
group: 'dev'
#name: 'user-srv'
#mysql:
#  host: 'localhost'
#  port: 3306
#  user: 'root'
#  password: '123456'
#  db: 'mxshop_goods_srv'
#
#consul:
#  host: '192.168.181.130'
#  port: 8500